# Generated by Django 3.1.7 on 2021-10-01 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_auto_20211001_2322'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='order_id',
            new_name='id',
        ),
    ]
