# Generated by Django 3.1.7 on 2021-10-01 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_auto_20211001_2355'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='id',
            new_name='order_id',
        ),
    ]
