# Generated by Django 3.1.7 on 2021-10-04 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_auto_20211002_0008'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderUpdates',
            fields=[
                ('update_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_id', models.IntegerField(default='')),
                ('update_desc', models.CharField(max_length=200)),
                ('timestamp', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
